# .github/labeler.yml

version: v1

labels:
  - label: 'lab0'
    sync: true
    matcher:
      title: '*Лабораторная №0'
      
  - label: 'lab1'
    sync: true
    matcher:
      title: '*Лабораторная №1'
      
  - label: 'lab2'
    sync: true
    matcher:
      title: '*Лабораторная №2'
      
  - label: 'lab3'
    sync: true
    matcher:
      title: '*Лабораторная №3'
      
  - label: 'lab4'
    sync: true
    matcher:
      title: '*Лабораторная №5'
      
  - label: 'lab6'
    sync: true
    matcher:
      title: '*Лабораторная №6'
      
  - label: 'lab7'
    sync: true
    matcher:
      title: '*Лабораторная №7'
